### ISSUE TITLE
Submission Video Structure 

### ISSUE THREAD

**Issue by tropicalchancer** [luoto/chingu-frontend#123]
Hey all, looking for feedback on the video submission structure when you have a minute. 🙏 

**1 - Community showcase Pt. 1**
Clips of chingus from around the world, showcasing the diversity and teeing-up that our project submission will generate real impact. (see other Submission Video ticket for more info)

**2 - Verbal introduction to Chingu & project submission** 
This is the first part of our first submission video. 

**3 -  Walkthru of Client**
Walk through of the new client, including newsfeed & project page. 

**4 - Community Showcase Pt. 2**
Quick run-through of what is included in a Voyage:
- Peek at a slack chats in action
- View of the github repos on a Voyage
- Quick view of what a Project Showcase looks like

**5 - What Could Be**
1-5 establishes the *Now*, I'd like to end off with a *What Could Be* with the introduction of this project into the wild. This would be related to Chingu's larger goals: 
- A collaboration capital on the web for tech learners
- Tokyo 2020 Challenge: 2020 finished team projects by the Tokyo Olympics
- Long-range Moonshot: 500 teams launched per session

![image](https://user-images.githubusercontent.com/15321359/44615692-1a416980-a873-11e8-9a4b-092d5105a60c.png)

**Notes:** 
 - The above structure will likely land somewhere between 3-4 minutes long.  They suggested 2 minutes for the regionals, and regional winners were all over the map. I'm personally okay with going over it in order to get what we need to get across, but curious what everything thinks on this. For context: The longest video of the regional winners was 4:35 minutes long and got Second in North America, so there is precedent to have a longer video if need-be. 

 - The admin panel walkthrough is removed in this schedule. The reasoning is that the functionality won't be there and could hurt our chances (or disqualify us), though we could add briefly mention it in the video as something we're working on, as well as show a screenshot or two in the Screenshot section of the submission page. 

**Feedback greatly appreciated!**

**Comment by WorldOfCode22** [comment]
I would aim for 4 minutes that way we are significantly less then 4:35 and still have a lot of time to talk about things. I love the general layout and I do think ended it with what chingu could be is a great idea for several reasons. First the video starts with the welcome to chingu clips and ends with what we could be. So we start with here is what we are and here is a sliver of what we could be. I would spend a good minute or so on the last part of what we can be because it shows how we are planing to grow and touch more lives. One piece that maybe wroth ending with is a couple of quotes about people who are drastically happier thanks to chingu. Then as a last note say something like “we hope in the future thanks to these improvements we can help more people achieve their dreams” if we can accomplish this we show that we have a world community, that we are improving now and in the future, that we have ambitious goals, that we have dramatic impact on some people lives and that we are useing this platform and these improvements to help people in many ways from all over the world.
