### ISSUE TITLE
Feed Refresh

### ISSUE THREAD

**Issue by luoto** [luoto/chingu-frontend#124]
parent of #103
child of #68

- setInterval when mounts
   - query client for when newsfeed was last checked, set interval timer accordingly
   - every time setInterval calls cb, update last checked value on client.
- clearInterval when component unmounts

Hide loader on refetches (?)

**Comment by thinktwice13** [comment]
Setting `fetchPolicy` based on localStorage lastCheck does not work because the policy is set only once per **mount**, not per query. 

`options={{ pollInterval: 5*60*1000  }}` is our best options for now.
Also doesn't set `loading = true` so we don't have to handle that ourselves

Looking into ways to redirect queries to cache if remounted under 5 minutes.
